[HOPSWORKS-2750] Git image
logicalclocks/hops-hadoop-chef pull request #352
Opened 2021-11-22 09:33 UTC by gibchikafa

2021-12-09 08:17 UTC, jimdowling reviewed
Add a version to the git image

2021-12-09 08:17 UTC, jimdowling commented on attributes/default.rb
> +default['hops']['docker']['git']['image']['name'] = "git"
You should add a version for this git image
default['hops']['docker']['git']['image']['version'] = "0.1"

2021-12-09 08:17 UTC, jimdowling commented on attributes/default.rb
> +default['hops']['docker']['git']['download_url']  = "#{node['download_url']}/kube/docker-images/#{node['hops']['docker_img_version']}/git.tar"
git-#{node['hops']['docker']['git']['image']['version']}.tar

2021-12-09 08:17 UTC, jimdowling commented on recipes/docker_registry.rb
> +  download_git_command = " wget --user #{node['install']['enterprise']['username']} --password #{node['install']['enterprise']['password']} #{git_image_url}"
Check to see if it has already been downloaded (this version).
Delete existing version and overwrite it.

2021-12-09 08:17 UTC, jimdowling commented on recipes/docker_registry.rb
> +       #{download_git_command} -O #{Chef::Config['file_cache_path']}/#{git_filename}
Again, overwrite it if it's already there. In case there was a problem downloading it (incomplete file) - easier to just delete and download again.

2022-01-09 22:44 UTC, jimdowling approved these changes
Would have preferred to see a version for the git image

2022-01-25 09:42 UTC, SirOibaf requested changes
Jim's comments are valid and need to be addressed.

2022-01-27 23:31 UTC, SirOibaf approved these changes

2022-01-27 23:31 UTC, merged