Hopsworks 3127
logicalclocks/hops-hadoop-chef pull request #374
Opened 2022-05-09 07:58 UTC by gibchikafa

2022-05-19 09:49 UTC, jimdowling requested changes

2022-05-19 09:49 UTC, jimdowling commented on recipes/docker_registry.rb
> +include_recipe "hops::docker_cgroup"
if exists_local("hopsworks", "default") 
  include_recipe "hops::docker_cgroup"
end

2022-05-19 09:49 UTC, jimdowling commented on recipes/docker.rb
> +include_recipe "hops::cadvisor"
if exists_local("hopsworks", "default")
  include_recipe "..."
end

2022-05-19 09:49 UTC, jimdowling commented on recipes/docker_cgroup.rb
> +  docker_cgroup_memory_hard_limit = "#{node['hops']['docker']['cgroup']['memory']['hard-limit']}"
For a "dynamic" way to set memory based on available memory in the host, do this:

create in attributes.default

node['hops']['docker']['cgroup']['memory']['hard-limit-default'] = 6
node['hops']['docker']['cgroup']['memory']['hard-limit'] = node['hops']['docker']['cgroup']['memory']['hard-limit-default']

node['hops']['docker']['cgroup']['memory']['soft-limit-default'] = 4
node['hops']['docker']['cgroup']['memory']['soft-limit'] = node['hops']['docker']['cgroup']['memory']['soft-limit-default']



Then in docker_cgroup.rb

available_memory_in_host_gbs = node.memory.total[/\d*/].to_i
default_hard_memory = node['hops']['docker']['cgroup']['memory']['hard-limit']
default_soft_memory = node['hops']['docker']['cgroup']['memory']['soft-limit']

available_memory_in_host_gbs = available_memory_in_host_gbs - default_hard_memory
excess_memory = available_memory_in_host_gbs - 30
excess_memory = excess_memory / 4

  # if the user overrides the hard-limit, then we should use their new hard-limit, and not add excess_memory
if node['hops']['docker']['cgroup']['memory']['hard-limit-default'] != node['hops']['docker']['cgroup']['memory']['hard-limit']
  excess_memory = 0
end

if node['hops']['docker']['cgroup']['memory']['soft-limit-default'] != node['hops']['docker']['cgroup']['memory']['soft-limit']
  excess_memory = 0
end

node.override['hops']['docker']['cgroup']['memory']['hard-limit'] = default_hard_memory + excess_memory
node.override['hops']['docker']['cgroup']['memory']['soft-limit'] = default_soft_memory + excess_memory

2022-05-24 07:53 UTC, robzor92 requested changes

2022-05-24 07:53 UTC, robzor92 commented on attributes/default.rb
> +default['hops']['docker']['cgroup']['cpu']['quota']                  = 70
```suggestion
default['hops']['docker']['cgroup']['cpu']['quota']                  = 80
```

2022-05-24 07:53 UTC, robzor92 commented on metadata.rb
> +=======
```suggestion
```

2022-05-24 07:53 UTC, robzor92 commented on metadata.rb
> +<<<<<<< HEAD
```suggestion
```

2022-05-24 07:53 UTC, robzor92 commented on metadata.rb
> +>>>>>>> Manage and monitor resource usage for Docker containers
```suggestion
```

2022-05-24 07:53 UTC, robzor92 commented on attributes/default.rb
> +default['hops']['docker']['cgroup']['cpu']["period"]                 = 100000
```suggestion
default['hops']['docker']['cgroup']['cpu']['period']                 = 100000
```

2022-05-24 07:53 UTC, robzor92 commented on attributes/default.rb
> +default['hops']['docker']['cgroup']['memory']['hard-limit-default']  = "6GB"
Why do you have a _default['hops']['docker']['cgroup']['memory']['hard-limit-default']_ and a _default['hops']['docker']['cgroup']['memory']['hard-limit']_, shouldn't it be enough with one of them?

2022-05-24 07:53 UTC, robzor92 commented on attributes/default.rb
> +default['hops']['docker']['cgroup']['memory']['hard-limit-default']  = "6GB"
Like only keep default['hops']['docker']['cgroup']['memory']['hard-limit'] and just set it to 6GB.

2022-05-24 07:53 UTC, robzor92 commented on recipes/cadvisor.rb
> +=begin
Why is this commented out?

2022-05-24 07:53 UTC, robzor92 commented on recipes/docker_cgroup.rb
> +  cpu_quota_period = node['hops']['docker']['cgroup']['cpu']["period"]
```suggestion
  cpu_quota_period = node['hops']['docker']['cgroup']['cpu']['period']
```

2022-05-24 07:53 UTC, robzor92 commented on attributes/default.rb
> +default['hops']['docker']['cgroup']['cpu']["period"]                 = 100000
Also can you add this attribute to metadata.rb?

2022-05-30 10:16 UTC, robzor92 requested changes

2022-05-30 10:16 UTC, robzor92 commented on recipes/docker_cgroup.rb
> +docker_dedault_soft_limit_memory_bytes = (node['hops']['docker']['cgroup']['memory']['soft-limit-default'].gsub("GB", "").to_i) * 1073741824
```suggestion
docker_default_soft_limit_memory_bytes = (node['hops']['docker']['cgroup']['memory']['soft-limit-default'].gsub("GB", "").to_i) * 1073741824
```

2022-05-30 10:16 UTC, robzor92 commented on recipes/docker_cgroup.rb
> +if excess_memory < 0 || (docker_default_hard_limit_memory_bytes != docker_hard_limit_memory_bytes || docker_dedault_soft_limit_memory_bytes != docker_soft_limit_memory_bytes)
```suggestion
if excess_memory < 0 || (docker_default_hard_limit_memory_bytes != docker_hard_limit_memory_bytes || docker_default_soft_limit_memory_bytes != docker_soft_limit_memory_bytes)
```

2022-05-30 10:16 UTC, robzor92 commented on recipes/docker_cgroup.rb
> +# dyanamic memory allocation
```suggestion
# dynamic memory allocation
```

2022-05-30 10:16 UTC, robzor92 commented on recipes/docker_cgroup.rb
> +excess_memory = available_memory_in_host_bytes - (30 * 1073741824)
Add a comment that the assumption is that Hopsworks services require 30GB.

2022-05-30 10:16 UTC, robzor92 commented on templates/default/cadvisor.service.erb
> +--storage_driver_password=root \
Is it a security risk by exposing this password here? Are users able to connect to it and what information can they get?

2022-06-09 14:59 UTC, robzor92 approved these changes

2022-06-09 15:51 UTC, jimdowling approved these changes

2022-06-09 15:53 UTC, merged