HOPSFS-20: Added support for AWS end point and AWS credentials
logicalclocks/hops-hadoop-chef pull request #388
Opened 2022-09-02 09:06 UTC by smkniazi

2022-10-09 22:44 UTC, SirOibaf requested changes

2022-10-09 22:44 UTC, SirOibaf commented on recipes/default.rb
> +  directory "/home/#{node['hops']['hdfs']['user']}/.aws" do
Use this method to assemble the home directory of the user: https://github.com/logicalclocks/conda-chef/blob/60639d26a5644dd65b462607a038e8267c80d557/libraries/default.rb#L14

2022-10-09 22:44 UTC, SirOibaf commented on recipes/default.rb
> +  template "/home/#{node['hops']['hdfs']['user']}/.aws/credentials" do
Same as above.

2022-10-25 13:58 UTC, SirOibaf requested changes

2022-10-25 14:01 UTC, smkniazi commented on recipes/_config.rb
> +  node.override['hops']['dist_url']    = "https://repo.hops.works/dev/salman/hadoop-3.2.0.7-EE-RC0.tar.gz"
done

2022-10-25 14:04 UTC, SirOibaf approved these changes

2022-10-26 07:24 UTC, merged